--- 
abstract: Automatically Mess With @ARGV's Encoding
author: 
  - Copyright (c) 2008 Daisuke Maki <daisuke@endeworks.jp>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.69
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Encode-Argv
no_index: 
  directory: 
    - inc
    - t
requires: 
  Encode: 0
  perl: 5.8.0
version: 0.00001
